spring.application.name=foodstore

# CONFIGURACIÓN DE BASE DE DATOS H2 (En Memoria)
spring.datasource.url=jdbc:h2:mem:foodstoredb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# CONFIGURACIÓN DE HIBERNATE (ORM)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# HABILITAR CONSOLA VISUAL DE H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console